/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
  @Test
  public void nullList() {
    ArrayList<Double> q1 = new ArrayList<>(Arrays.asList(2.0, 3.0, 5.4));

    ArrayList<Double> q2 = new ArrayList<>(Arrays.asList(1.2, 2.5, 3.4));
    ArrayList<Double> q3 = null;
    ArrayList<Double> q4 = new ArrayList<>(Arrays.asList(77.2, 44.5, 3.9));
    ;
    new App();
    assertEquals(App.quarterlyAverage(q1, q2, q3, q4), -1);
  }

  @Test
  public void testEmptyList() {
    ArrayList<Double> q1 = new ArrayList<>(Arrays.asList());

    ArrayList<Double> q2 = new ArrayList<>(Arrays.asList());
    ArrayList<Double> q3 = new ArrayList<>(Arrays.asList());
    ArrayList<Double> q4 = new ArrayList<>(Arrays.asList());
    new App();
    assertEquals(App.quarterlyAverage(q1, q2, q3, q4), -1);
  }

  @Test
  public void testNormalInput() {
    ArrayList<Double> q1 = new ArrayList<>(Arrays.asList(10.0, 10.0, 10.0, 10.0));
    ArrayList<Double> q2 = new ArrayList<>(Arrays.asList(10.0, 10.0, 10.0, 10.0));
    ArrayList<Double> q3 = new ArrayList<>(Arrays.asList(10.0, 10.0, 10.0, 10.0));
    ;
    ArrayList<Double> q4 = new ArrayList<>(Arrays.asList(10.0, 10.0, 10.0, 10.0));
    ;
    new App();
    assertEquals(App.quarterlyAverage(q1, q2, q3, q4), 40.0);
  }

  @Test
  public void testNegativeResult() {
    ArrayList<Double> q1 = new ArrayList<>(Arrays.asList(-10.0, -10.0, -10.0, -10.0));
    ArrayList<Double> q2 = new ArrayList<>(Arrays.asList(-10.0, -10.0, -10.0, -10.0));
    ArrayList<Double> q3 = new ArrayList<>(Arrays.asList(-10.0, -10.0, -10.0, -10.0));
    ;
    ArrayList<Double> q4 = new ArrayList<>(Arrays.asList(-10.0, -10.0, -10.0, -10.0));
    ;
    new App();
    assertNotEquals(App.quarterlyAverage(q1, q2, q3, q4), -40.0);
  }

  @Test
  public void testNotFound() {
    ArrayList<Double> q1 = new ArrayList<>(Arrays.asList(10.0, 10.0, 10.0, 10.0));
    ArrayList<Double> q2 = new ArrayList<>(Arrays.asList(10.0, 10.0, 10.0, 10.0));
    ArrayList<Double> q3 = new ArrayList<>(Arrays.asList(10.0, 10.0, 10.0, 10.0));
    ;
    ArrayList<Double> q4 = new ArrayList<>(Arrays.asList(10.0, 10.0, 10.0, 10.0));
    ;
    new App();
    assertNotEquals(App.quarterlyAverage(q1, q2, q3, q4), 30.0);
  }

}
